"use client"

import { Sparkles, Target, Zap, ArrowRight, ExternalLink } from "lucide-react"
import { Button } from "@/components/common/Button"
import Link from "next/link"

const RECOMMENDED_JOBS = [
  { id: 10, title: "Lead React Engineer", company: "Meta", match: 96, reason: "Your 5 years of React experience and recent project using Next.js 14 directly aligns with their tech stack migration requirements." },
  { id: 11, title: "Frontend Architect", company: "Vercel", match: 91, reason: "You have strong open-source contributions in the React ecosystem, which is highly valued by this team." },
]

const RECOMMENDED_SKILLS = [
  { name: "GraphQL", importance: "High", timeframe: "2 weeks", reason: "45% of Senior Frontend roles you saved require GraphQL knowledge." },
  { name: "AWS CloudFront", importance: "Medium", timeframe: "1 week", reason: "Employers in your target salary range ($130k+) frequently look for edge computing experience." },
]

export default function AIRecommendationsPage() {
  return (
    <div className="max-w-5xl space-y-8">
      
      <div>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-3">
          <Sparkles className="h-8 w-8 text-primary" /> Smart Recommendations
        </h1>
        <p className="text-muted-foreground mt-2">
          Personalized insights generated by our Agentic AI, based on your parsed resume, search history, and saved jobs.
        </p>
      </div>

      <div className="grid lg:grid-cols-2 gap-8">
        
        {/* Job Recommendations */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <Target className="h-5 w-5 text-blue-500" /> Highly Matched Roles
          </h2>
          
          <div className="space-y-4">
            {RECOMMENDED_JOBS.map(job => (
              <div key={job.id} className="bg-card border border-blue-500/20 rounded-2xl p-6 shadow-sm relative overflow-hidden group">
                <div className="absolute top-0 right-0 bg-blue-500 text-white text-xs font-bold px-3 py-1.5 rounded-bl-xl shadow-sm">
                  {job.match}% Match
                </div>
                
                <h3 className="font-bold text-lg mt-2 pr-12">{job.title}</h3>
                <p className="text-muted-foreground text-sm mb-4">{job.company}</p>
                
                <div className="bg-blue-500/5 p-4 rounded-xl border border-blue-500/10 mb-6">
                  <p className="text-sm leading-relaxed text-foreground/90">
                    <strong className="text-blue-600 block mb-1">Why this match?</strong>
                    {job.reason}
                  </p>
                </div>
                
                <Link href={`/jobs/${job.id}`}>
                  <Button variant="outline" className="w-full gap-2 border-blue-500/30 hover:bg-blue-500/10 hover:text-blue-600 transition-colors">
                    Review Job <ArrowRight className="h-4 w-4" />
                  </Button>
                </Link>
              </div>
            ))}
          </div>
        </div>

        {/* Skill / Gap Recommendations */}
        <div className="space-y-6">
          <h2 className="text-xl font-bold flex items-center gap-2">
            <Zap className="h-5 w-5 text-yellow-500" /> Skill Gap Analysis
          </h2>
          
          <div className="space-y-4">
            {RECOMMENDED_SKILLS.map((skill, idx) => (
              <div key={idx} className="bg-card border border-yellow-500/20 rounded-2xl p-6 shadow-sm">
                
                <div className="flex justify-between items-start mb-3">
                  <h3 className="font-bold text-lg">{skill.name}</h3>
                  <span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${
                    skill.importance === "High" ? "bg-red-500/10 text-red-600" : "bg-orange-500/10 text-orange-600"
                  }`}>
                    {skill.importance} Priority
                  </span>
                </div>
                
                <p className="text-sm text-muted-foreground leading-relaxed mb-4">
                  {skill.reason}
                </p>
                
                <div className="flex items-center justify-between pt-4 border-t border-yellow-500/10">
                  <span className="text-xs text-muted-foreground font-medium">Est. Time: {skill.timeframe}</span>
                  <Link href="#" className="text-xs font-bold text-yellow-600 flex items-center gap-1 hover:underline">
                    Find Courses <ExternalLink className="h-3 w-3" />
                  </Link>
                </div>
              </div>
            ))}
          </div>

          <div className="bg-muted/30 border border-dashed rounded-2xl p-6 text-center">
            <p className="text-sm text-muted-foreground mb-4">Want a complete roadmap to level up your career?</p>
            <Link href="/ai-roadmap">
              <Button variant="default">Generate Career Roadmap</Button>
            </Link>
          </div>
        </div>

      </div>
    </div>
  )
}
